### ISSUE TITLE
Memory leak on kill: msg_task_t being executed

### ISSUE THREAD

**Issue by mpoquet** [oar-team/batsim#33]
When a MSG-like job is killed, its associated msg_task is not freed.
Unfortunately, freeing the msg_task leads to a SG deadlock :(.

**Comment by mickours** [comment]
Now that MSG is gone, can we close this one @mpoquet ?

**Comment by mpoquet** [comment]
As I write these lines (548cd4b) MSG is not gone yet :(.

Parallel tasks are still created by `MSG_parallel_task_create` and executed with `MSG_parallel_task_execute`. Parallel tasks cannot be killed in s4u yet, but we (Martin and I) recently worked on parallel tasks in s4u for this purpose.

**Comment by Mommessc** [comment]
MSG is gone forever now.
But if I remember @mpoquet you spotted some memory leaks anyway?

**Comment by mpoquet** [comment]
Closing this issue as MSG is gone. Please open another issue to track memory leaks if needed.
