### ISSUE TITLE
Jobs submitted at the same time should be in the same message

### ISSUE THREAD

**Issue by mpoquet** [oar-team/batsim#35]

**Comment by mickours** [comment]
Not sure that this would be useful: It would break the protocol and most of the jobs needs to be managed separately by the scheduler. Also, the gain in the protocols message size is quite low.

@mpoquet do you have use case for this?

**Comment by mpoquet** [comment]
Mmh sorry I meant in the same **network message**, not in the same **protocol event**.

As a use case I can think of batches of jobs that are submitted together, notably for those submitted at time 0 for *offline* scheduling problems. Currently, I think that offline algorithms must wait two **messages** containing job submissions, while one message should be enough.

I think that this feature is very easy to implement. Within Batsim, we should just send a container of jobs rather one job in internal messages from the job submitter to the server.

A test should be added about it, this feature may already work as the *sleep* calls in the job submitters have been modified in the past.

**Comment by mpoquet** [comment]
Note: the ``same_submit_time`` test only checks that the messages that should be submitted at the same time are sent in a deterministic order (ordered by job_id).

**Comment by Mommessc** [comment]
Up!

**Comment by mpoquet** [comment]
Hello @Mommessc! I have no update about this, it may already work or not.  It should be easy to implement : Just send a vector of jobs instead of one job in the internal message from the submitter to the server.

**Comment by mpoquet** [comment]
Merged in 22d2f9e. Thanks @Mommessc!
