### ISSUE TITLE
Bad consumed power when doing computations?

### ISSUE THREAD

**Issue by mpoquet** [oar-team/batsim#38]
It seems that homogeneous MSG jobs do not consume energy:
- while the machine is idle, 95 W are consumed
- while a job is being computed, 95 W are consumed :(

But the computation power state should use 190.738 W when computing the job.
``` xml
<prop id="watt_per_state" value="95.0:95.0:190.738"/>
```

![energy_plot](https://user-images.githubusercontent.com/3502831/27148102-56cc37f4-513f-11e7-9daf-cf23a473b9d2.png)

### Run the simulation
``` bash
cd ${BATSIM_DIR}
export EVALYS_DIR=/path/to/evalys/directory
tools/experiments/execute_instances.py test/test_energy_minimal.yaml
```
### Analysis
The ``/tmp/batsim_tests/energy_minimal/results/9f89a160/energy_plot.png`` file should now exist and be visualized by any tool you like.

**Comment by mpoquet** [comment]
Also confirmed with up-to-date SimGrid (commit 863aeead8 of 2017-06-13 22:15).
![energy_plot](https://user-images.githubusercontent.com/3502831/27154683-3c042064-5156-11e7-963b-a53bad6ab35b.png)

**Comment by mpoquet** [comment]
The problem came from SimGrid:
- Issue : https://github.com/simgrid/simgrid/issues/189
- Fixed by simgrid/simgrid@e96681fb8

Up-to-date SimGrid should be used to do energy experiments with Batsim.

![energy_plot](https://user-images.githubusercontent.com/3502831/27192858-2736aa06-51fd-11e7-8de1-699f8a028cf4.png)

**Comment by mpoquet** [comment]
Issue is tracked on https://github.com/simgrid/simgrid/issues/189.

**Comment by Mommessc** [comment]
Up!
Is this fixed now?
