### ISSUE TITLE
Sending `EXECUTE_JOB` with a wrong number of nodes

### ISSUE THREAD

**Issue by adfaure** [oar-team/batsim#40]
If I send `EXECUTE_JOB` with fewer resources than the job needs, batsim will segfault.
edit: if the number of resources is greater, batsim doesn't care.

**Comment by mpoquet** [comment]
It's not a bug, it's a feature :D.
A buggy / not implemented yet feature at the moment :(.

Previously Batsim checked that the number of given resources exactly matched the job size.
However, a SMPI job can now be run with fewer resources, which allows to place several ranks on the same machine. This code has not be tested with other profiles, I will add a test about it and debug ;).

**Comment by mpoquet** [comment]
I can reproduce the issue.

**Comment by mpoquet** [comment]
@adfaure : Can you confirm that 0659e43 solved the problem?
A clear error message should now be displayed (hidden before a SimGrid backtrace).

**Comment by mpoquet** [comment]
Really using fewer resources than a job requested should work after 6e1e44f.
To do so, a mapping must be given with the EXECUTE_JOB message.
