### ISSUE TITLE
'-' should be allowed in sweep values

### ISSUE THREAD

**Issue by adfaure** [oar-team/batsim#42]
```
ERROR Invalid sweep variable workloads: the name got from dict {'filename': '/home/afaure/Projects
/rejectionix/experiments/01_rejection/run/workloads/extracted_CEA-Curie_60H_80util+-0.2_0.json', 'name': 
'CEA-Curie', 'platform': '/home/afaure/Projects/rejectionix/experiments/01_rejection/run/platforms
/platform_5544.xml'} (name=CEA-Curie, got either from the 'name' field if it exists or the first value 
otherwise) is not a valid identifier. It must be because it is used to create files.
```

**Comment by mpoquet** [comment]
Yes, this constraint should be removed.  
It has been introduced before **instance_id**. The **name** was used to create yaml files for each instance.

**Comment by mpoquet** [comment]
But the way to go is probably not to maintain these two scripts but to create better and more modular ones.
- https://gitlab.inria.fr/batsim/batsim/issues/7
- https://gitlab.inria.fr/batsim/batsim/issues/8
- https://gitlab.inria.fr/batsim/batsim/issues/13
