### ISSUE TITLE
Batsim: Infrastucture Simulator for Batch Scheduler

### ISSUE THREAD

**Issue by adfaure** [oar-team/batsim#44]
My proposal is to change the "official" description of Batsim.

**From:**
> Batch scheduler simulator: Focus on realism, facilitate comparison

**To (something like):**
> Infrastructure Simulator for Batch Scheduler

It is, of course, subject to discussion :)

**Comment by mpoquet** [comment]
I also believe that this description – and most of the readme btw – should be changed.

I'm not a big fan of the *batch* word, but as Batsim's name comes from it, I think it's okay…

**Comment by mickours** [comment]
Why not: Infrastructure Scheduling Simulator

It more generic and better fits batsim's features as we can do IO scheduling now.

**Comment by mickours** [comment]
Ok as @adfaure suggest here is something more specific:
infrastructure simulator for job and IO scheduling

I think we agreed on that, now we need to rewrite the readme and change the description accordingly.

**Comment by mickours** [comment]
Retrospectively, I'm still not sure on this but in the end, I changed the github description eventually :)

Still in TODO for the documentation.

**Comment by Mommessc** [comment]
How about adding "platform" or "resources" somewhere here?
Something like "Infrastructure simulator for jobs, I/Os and other resources management".

**Comment by mpoquet** [comment]
I close this issue as this seems fixed. Please reopen the issue if you do not agree.
