### ISSUE TITLE
Do you really needed MSG nowadays?

### ISSUE THREAD

**Issue by mquinson** [oar-team/batsim#53]
Hello,

MSG is now disabled by default in the git (released this week-end). You can still pass -Denable_msg=ON if you really need it, but I suspect you only use MSG_init nowadays and could easily finish your switch to S4U. Am I right?

For the record, here is a failed build job: https://framagit.org/simgrid/external-projects-ci/-/jobs/660769

Thanks, Mt

**Comment by mquinson** [comment]
According to https://github.com/oar-team/batsim/commit/98a518f9d36c1da5b9dd4d78bffeac82f34fac53 MSG is long gone in batsim, so I guess that our automatic builder is taking an old version of batsim. I don't see what's wrong with https://framagit.org/simgrid/external-projects-ci/blob/master/.gitlab-ci.yml however. Any nix guru around, maybe? ;)

**Comment by mickours** [comment]
Hi!

This comes from the fact that the tested version is pinned:
https://framagit.org/simgrid/external-projects-ci/blob/master/batsim/release.nix#L5

This commit is a bit dated: (2019-05-27) but it looks like it more or less point to the last release: 3.1.0.

@Millian do you have a new release planned?

**Comment by mpoquet** [comment]
Hello and thanks for the notification,

I remember merging `sayonara-msg` kind of branches some time ago, I think that Batsim no longer requires MSG.

I'll update simgrid-external-ci this afternoon.

**Comment by mquinson** [comment]
hello, 

is there any update on this one? simgrid-external-ci still seems broken (maybe because of something else).

**Comment by mpoquet** [comment]
Hello. No, batsim does not need MSG.

I updated the Nix recipe of `simgrid/external-projects-ci` and unpinned batsim's commit, batsim should be built from its latest master branch commit now.

Recent issues on `simgrid/external-projects-ci` seems to come from framagit's infrastructure and not the recipe though — we faced similar issues on framagit recently.
