### ISSUE TITLE
tools: Change profile type

### ISSUE THREAD

**Issue by igornardin** [oar-team/batsim#55]
I think that the profile type on swf_to_batsim_workload_compute_only.py is wrong. The script has 'msg_par_hg' in line 98, but I think that the correct value is 'parallel_homogeneous' (I have read in some place this changed). I changed locally and works perfectly.

File: [swf_to_batsim_workload_compute_only.py](https://github.com/oar-team/batsim/blob/master/tools/swf_to_batsim_workload_compute_only.py)

**Comment by mickours** [comment]
Thanks for pointing this. I've created a merge request that fix the issue.
