### ISSUE TITLE
Streamed output

### ISSUE THREAD

**Issue by mpoquet** [oar-team/batsim#6]
When large instances are executed, they might be stopped for many reasons : timeout reached, discharged battery, stopped by the user because it is too long... In these cases, nearly all Batsim's outputs are lost, as most are written at the end of the simulation.

It would be way better to write outputs throughout the simulation rather than what is currently done.
The Pajé trace outputting is already streamed, the same should be applied to other output files.

**Comment by Mommessc** [comment]
UP!
After discussion with @mickours we think that a flush of the buffers into the output files at regular time would do the trick.

**Comment by mpoquet** [comment]
This has been done for jobs by @Mommessc IIRC.
Closing this issue as it is super old and solved for the main output file. Please reopen it if needed for other output files.
