### ISSUE TITLE
Platforms: keyword watt_per_state changed for wattage_per_state

### ISSUE THREAD

**Issue by maelmadon** [oar-team/batsim#63]
I noticed that the host_energy plugin of SimGrid has changed between v3.25 and v3.28. 

It seems that the keywords `"watt_per_state" `and `"watt_off"` in the platforms have been renamed `"wattage_per_state"` and `"wattage_off"`. 

There are still references of these old names in Batsim, should we rename them all?

**Comment by mpoquet** [comment]
Oops, looks like I forgot to update some files :D.

I saw this when updating to SimGrid-3.28 (99eb65c) and updated the files used by the automated tests but not the other ones.
This should be fixed as of f1abf7c, thanks for the report!
